export const pageNames = {
  ru: { home: "Главная", "how-it-works": "Как это работает", tech: "Технологии", about: "О проекте", download: "Скачать", comparison: "Сравнение", "not-found": "404", roadmap: "Карта разработки", privacy: "Политика конфиденциальности", terms: "Пользовательское соглашение", news: "Новости", features: "Возможности", research: "Исследования", "privacy-architecture": "Архитектура приватности", sections: "Все разделы", glossary: "Глоссарий", test: "Проверь себя", help: "Что делать, если обманули" },
  en: { home: "Home", "how-it-works": "How It Works", tech: "Technology", about: "About Us", download: "Download", comparison: "Comparison", "not-found": "404", roadmap: "Roadmap", privacy: "Privacy Policy", terms: "Terms of Service", news: "News", features: "Features", research: "Research", "privacy-architecture": "Privacy Architecture", sections: "All sections", glossary: "Glossary", test: "Spot the Scam", help: "What to Do If Scammed" },
  es: { home: "Inicio", "how-it-works": "Cómo funciona", tech: "Tecnología", about: "Nosotros", download: "Descargar", comparison: "Comparación", "not-found": "404", roadmap: "Mapa de desarrollo", privacy: "Política de privacidad", terms: "Términos de uso", news: "Noticias", features: "Funciones", research: "Investigación", "privacy-architecture": "Arquitectura de privacidad", sections: "Todas las secciones", glossary: "Glosario", test: "Detecta la Estafa", help: "Qué Hacer Si Te Estafaron" },
  zh: { home: "首页", "how-it-works": "工作原理", tech: "技术", about: "关于我们", download: "下载", comparison: "对比", "not-found": "404", roadmap: "路线图", privacy: "隐私政策", terms: "用户协议", news: "新闻", features: "功能", research: "研究", "privacy-architecture": "隐私架构", sections: "所有板块", glossary: "词汇表", test: "识破骗局", help: "被骗了怎么办" },
  tr: { home: "Ana Sayfa", "how-it-works": "Nasıl Çalışır", tech: "Teknoloji", about: "Hakkımızda", download: "İndir", comparison: "Karşılaştırma", "not-found": "404", roadmap: "Yol Haritası", privacy: "Gizlilik Politikası", terms: "Kullanıcı Sözleşmesi", news: "Haberler", features: "Özellikler", research: "Araştırma", "privacy-architecture": "Gizlilik Mimarisi", sections: "Tüm bölümler", glossary: "Sözlük", test: "Aldatmacayı Yakala", help: "Dolandırılırsan Ne Yapmalısın" },
  hi: { home: "मुख्य", "how-it-works": "यह कैसे काम करता है", tech: "तकनीक", about: "हमारे बारे में", download: "डाउनलोड करें", comparison: "तुलना", "not-found": "404", roadmap: "रोडमैप", privacy: "गोपनीयता नीति", terms: "उपयोग की शर्तें", news: "समाचार", features: "फ़ीचर्स", research: "अनुसंधान", "privacy-architecture": "प्राइवेसी आर्किटेक्चर", sections: "सभी अनुभाग", glossary: "शब्दावली", test: "धोखा पहचानें", help: "धोखा लगे तो क्या करें" },
  ar: { home: "الرئيسية", "how-it-works": "كيف يعمل", tech: "التكنولوجيا", about: "من نحن", download: "تنزيل", comparison: "مقارنة", "not-found": "404", roadmap: "خريطة الطريق", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام", news: "الأخبار", features: "الميزات", research: "الأبحاث", "privacy-architecture": "معمارية الخصوصية", sections: "جميع الأقسام", glossary: "مسرد", test: "اكتشف الاحتيال", help: "ماذا تفعل إذا تم خداعك" },
  pt: { home: "Início", "how-it-works": "Como Funciona", tech: "Tecnologia", about: "Sobre Nós", download: "Baixar", comparison: "Comparação", "not-found": "404", roadmap: "Roteiro", privacy: "Política de Privacidade", terms: "Termos de Uso", news: "Notícias", features: "Recursos", research: "Pesquisa", "privacy-architecture": "Arquitetura de Privacidade", sections: "Todas as seções", glossary: "Glossário", test: "Detecte o Golpe", help: "O Que Fazer Se Golpeado" },
  fr: { home: "Accueil", "how-it-works": "Comment ça marche", tech: "Technologie", about: "À Propos", download: "Télécharger", comparison: "Comparaison", "not-found": "404", roadmap: "Feuille de route", privacy: "Politique de confidentialité", terms: "Conditions d'utilisation", news: "Actualités", features: "Fonctionnalités", research: "Recherche", "privacy-architecture": "Architecture de confidentialité", sections: "Toutes les rubriques", glossary: "Glossaire", test: "Repérez l'Arnaque", help: "Que Faire en Cas d'Arnaque" },
  de: { home: "Startseite", "how-it-works": "Wie es funktioniert", tech: "Technologie", about: "Über Uns", download: "Herunterladen", comparison: "Vergleich", "not-found": "404", roadmap: "Roadmap", privacy: "Datenschutzerklärung", terms: "Nutzungsbedingungen", news: "Neuigkeiten", features: "Funktionen", research: "Forschung", "privacy-architecture": "Datenschutz-Architektur", sections: "Alle Bereiche", glossary: "Glossar", test: "Trick Erkennen", help: "Was Tun Bei Betrug" },
  ja: { home: "ホーム", "how-it-works": "仕組み", tech: "テクノロジー", about: "私たちについて", download: "ダウンロード", comparison: "比較", "not-found": "404", roadmap: "ロードマップ", privacy: "プライバシーポリシー", terms: "利用規約", news: "ニュース", features: "機能", research: "研究", "privacy-architecture": "プライバシー設計", sections: "すべてのセクション", glossary: "用語集", test: "詐欺を見抜く", help: "騙された場合の対処法" }
};
